table Orders
	lineageTag: 7c709350-35d7-48ad-ad9a-d74d94ebff2c

	column 'Row ID'
		dataType: int64
		formatString: 0
		lineageTag: 369ca095-e9d1-47ab-b2a1-1f4f0a3ef3e3
		summarizeBy: count
		sourceColumn: Row ID

		annotation SummarizationSetBy = Automatic

	column 'Order ID'
		dataType: string
		lineageTag: 7b60d905-352d-4bce-a079-96e4e710986f
		summarizeBy: none
		sourceColumn: Order ID

		annotation SummarizationSetBy = Automatic

	column 'Order Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: 7b74af67-73b3-4b82-8063-5965db0b0562
		summarizeBy: none
		sourceColumn: Order Date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Date'
		dataType: dateTime
		formatString: Long Date
		lineageTag: c6b9a0b9-505b-406f-a087-28442f4e4faa
		summarizeBy: none
		sourceColumn: Ship Date

		variation Variation
			isDefault
			relationship: 57a40662-db25-42f4-bdb7-81f6018b7c08
			defaultHierarchy: LocalDateTable_1d345815-6fbd-4080-acf8-9929eb5be3a2.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Ship Mode'
		dataType: string
		lineageTag: daf74b81-ae6a-4ffb-b6de-8cd855824244
		summarizeBy: none
		sourceColumn: Ship Mode

		annotation SummarizationSetBy = Automatic

	column 'Customer ID'
		dataType: string
		lineageTag: 1fff94b5-f747-434a-9b61-ceaa2264e702
		summarizeBy: none
		sourceColumn: Customer ID

		annotation SummarizationSetBy = Automatic

	column 'Customer Name'
		dataType: string
		lineageTag: 5d081b78-eda7-4ad3-8a40-5627888ee3ea
		summarizeBy: none
		sourceColumn: Customer Name

		annotation SummarizationSetBy = Automatic

	column Segment
		dataType: string
		lineageTag: 4799e7fa-ea32-4eb3-9701-489f1f53073a
		summarizeBy: none
		sourceColumn: Segment

		annotation SummarizationSetBy = Automatic

	column Country/Region
		dataType: string
		lineageTag: 9109f3d4-93ac-4dc4-a524-a4f2357fba76
		summarizeBy: none
		sourceColumn: Country/Region

		annotation SummarizationSetBy = Automatic

	column City
		dataType: string
		lineageTag: 5e040521-bdf3-405d-a09b-ebedc99dfa29
		summarizeBy: none
		sourceColumn: City

		annotation SummarizationSetBy = Automatic

	column State/Province
		dataType: string
		lineageTag: fc6a5d86-f9b3-4cfd-985a-befb763ff904
		summarizeBy: none
		sourceColumn: State/Province

		annotation SummarizationSetBy = Automatic

	column 'Postal Code'
		dataType: string
		lineageTag: ac26fd91-0a78-4cb6-87b0-103b041b9aa2
		summarizeBy: none
		sourceColumn: Postal Code

		annotation SummarizationSetBy = Automatic

	column Region
		dataType: string
		lineageTag: 50fea3c4-020c-470d-9229-abd5e3ce5dc7
		summarizeBy: none
		sourceColumn: Region

		annotation SummarizationSetBy = Automatic

	column 'Product ID'
		dataType: string
		lineageTag: f05b95eb-4b8b-4684-9a76-9458831d891b
		summarizeBy: none
		sourceColumn: Product ID

		annotation SummarizationSetBy = Automatic

	column Category
		dataType: string
		lineageTag: 50ee2594-54bf-48f6-a9c4-c8fa8fc876f6
		summarizeBy: none
		sourceColumn: Category

		annotation SummarizationSetBy = Automatic

	column Sub-Category
		dataType: string
		lineageTag: e5edf4ae-0184-4279-8235-5bcf143b4998
		summarizeBy: none
		sourceColumn: Sub-Category

		annotation SummarizationSetBy = Automatic

	column 'Product Name'
		dataType: string
		lineageTag: 6987aa11-31f2-4ac4-9c5d-1d9177192c69
		summarizeBy: none
		sourceColumn: Product Name

		annotation SummarizationSetBy = Automatic

	column Sales
		dataType: double
		lineageTag: 576b6937-7608-4e44-a62e-edca5b933e23
		summarizeBy: sum
		sourceColumn: Sales

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Quantity
		dataType: int64
		formatString: 0
		lineageTag: de11f686-702c-42c1-8007-20ce99cb77a0
		summarizeBy: sum
		sourceColumn: Quantity

		annotation SummarizationSetBy = Automatic

	column Discount
		dataType: double
		lineageTag: 0ff62177-0566-421a-a65d-7daa1798c4e1
		summarizeBy: sum
		sourceColumn: Discount

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Profit
		dataType: double
		lineageTag: 61607a4f-2063-47ac-9878-7d63434593cf
		summarizeBy: sum
		sourceColumn: Profit

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Orders = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents("E:\PORTFOLIO\POWER BI\E-commerce Sales Report\dataset\Orders.csv"),[Delimiter=",", Columns=21, Encoding=1252, QuoteStyle=QuoteStyle.None]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"Row ID", Int64.Type}, {"Order ID", type text}, {"Order Date", type date}, {"Ship Date", type date}, {"Ship Mode", type text}, {"Customer ID", type text}, {"Customer Name", type text}, {"Segment", type text}, {"Country/Region", type text}, {"City", type text}, {"State/Province", type text}, {"Postal Code", type text}, {"Region", type text}, {"Product ID", type text}, {"Category", type text}, {"Sub-Category", type text}, {"Product Name", type text}, {"Sales", type number}, {"Quantity", Int64.Type}, {"Discount", type number}, {"Profit", type number}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

